- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
    - id: yapf

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: trailing-whitespace
    - id: flake8
